export { StoreZoneManager } from './StoreZoneManager'
export { ZONES, getZoneDefinition } from './catalog'
export { defineZone } from './contracts'
export { validateZones } from './ZoneValidator'
export { CommercialZoneManager, DEFAULT_COMMERCIAL_SECTORS } from './CommercialZoneManager'
export type { ZoneCell, ZoneConstraints, ZoneCostDefinition, ZoneDefinition, ZoneSummary } from './contracts'
export type { ZoneBoundaryEdge, ZoneComponentValidation, ZoneValidationGrid, ZoneValidationIssue, ZoneValidationIssueCode, ZoneValidationReport } from './ZoneValidator'
export type { CommercialSectorDefinition, CommercialZoneCell, CommercialZoneCoverage, CommercialZoneInstance, CommercialZoneState } from './CommercialZoneManager'